create table if not exists admin_bootstrap_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  email text,
  event_type text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists admin_bootstrap_events_user_id_idx
  on admin_bootstrap_events (user_id);
