import type {
  LaunchLessonDefinition,
  ProjectTemplateDefinition,
} from '@/features/domain/types'

import { applyFoundationVoiceovers } from './foundation-voiceovers'

function buildHintLayers(
  repeatGoal: string,
  showBlock: string,
  remedialCopy: string,
) {
  return [
    { id: 'repeat-goal', mode: 'repeat_goal' as const, copy: repeatGoal },
    { id: 'show-block', mode: 'show_block' as const, copy: showBlock },
    {
      id: 'offer-remedial',
      mode: 'offer_remedial' as const,
      copy: remedialCopy,
      remedialLessonId: 'remedial-click-trigger',
    },
  ]
}

function step(
  id: string,
  title: string,
  instruction: string,
  allowedBlocks: string[],
  requiredBlockTypes: string[],
) {
  return { id, title, instruction, allowedBlocks, requiredBlockTypes }
}

export const launchTemplates: ProjectTemplateDefinition[] = [
  {
    id: 'forest-meetup-stage',
    name: '森林见面会舞台',
    starterScene: 'forest',
    starterCharacters: ['fox', 'rabbit'],
  },
  {
    id: 'meadow-journey-stage',
    name: '草地旅行舞台',
    starterScene: 'meadow',
    starterCharacters: ['fox', 'bird'],
  },
  {
    id: 'garden-interaction-stage',
    name: '花园互动舞台',
    starterScene: 'garden',
    starterCharacters: ['butterfly', 'frog'],
  },
  {
    id: 'forest-graduation-show',
    name: '动物朋友毕业演出',
    starterScene: 'forest-stage',
    starterCharacters: ['fox', 'bear'],
  },
]

export const launchLessons: LaunchLessonDefinition[] = [
  {
    id: 'lesson-01-forest-hello',
    title: '小狐狸出场',
    goal: '让小狐狸从舞台一边走到另一边，完成第一次出场。',
    recommendedLevel: 'starter',
    steps: [
      step('step-1', '认识今天的主角', '先看看今天的小狐狸，等会儿我们要让它自己走上舞台。', ['when_start'], ['when_start']),
      step('step-2', '认识开始积木', '先放“开始时”，告诉小狐狸什么时候准备出场。', ['when_start'], ['when_start']),
      step('step-3', '让舞台准备好', '确认“开始时”放在最前面，舞台就准备好了。', ['when_start'], ['when_start']),
      step('step-4', '接上移动积木', '把“向右移动”接在后面，让小狐狸走上舞台。', ['when_start', 'move_right'], ['when_start', 'move_right']),
      step('step-5', '回看第一次出场', '点一下运行，看看小狐狸是不是已经顺利出场了。', ['when_start', 'move_right'], ['when_start', 'move_right']),
    ],
    rewardCardId: 'theme-forest-fox',
    phase: 'trial',
    mode: 'guided',
    sortOrder: 1,
    hintLayers: buildHintLayers(
      '先让小狐狸准备好出场，再接动作积木。',
      '把“开始时”放在最前面，再把“向右移动”接上去。',
      '先看一个很短的示意，再回来试一次。',
    ),
    parentAdvice: '请孩子演示一下小狐狸是怎么从舞台一边走到另一边的。',
  },
  {
    id: 'lesson-02-forest-greeting',
    title: '小狐狸打招呼',
    goal: '让小狐狸开口说一句欢迎的话。',
    recommendedLevel: 'starter',
    steps: [
      step('step-1', '回顾上节的小成果', '先回看小狐狸出场，等会儿我们要让它开口打招呼。', ['when_start'], ['when_start']),
      step('step-2', '认识说话积木', '这块“说一句话”积木可以让小狐狸开口说话。', ['when_start', 'say_line'], ['when_start']),
      step('step-3', '先让小狐狸准备好', '先放“开始时”，让小狐狸准备好出场。', ['when_start', 'say_line'], ['when_start']),
      step('step-4', '接上说话积木', '把“说一句话”接在后面，让小狐狸打个招呼。', ['when_start', 'say_line'], ['when_start', 'say_line']),
      step('step-5', '换一句自己的话', '从预设对白里选一句你喜欢的话，让小狐狸再说一次。', ['when_start', 'say_line'], ['when_start', 'say_line']),
    ],
    rewardCardId: 'theme-forest-rabbit',
    phase: 'trial',
    mode: 'guided',
    sortOrder: 2,
    hintLayers: buildHintLayers(
      '先让小狐狸准备好，再把说话积木接上去。',
      '试试把“说一句话”接在“开始时”的后面。',
      '先看一下“先开始，再说话”的小示意。',
    ),
    parentAdvice: '让孩子给你演示一下小狐狸说了什么，再试着换一句自己的对白。',
  },
  {
    id: 'lesson-03-forest-story',
    title: '森林里的第一次见面',
    goal: '把动作和对白连起来，完成第一个完整小故事。',
    recommendedLevel: 'starter',
    steps: [
      step('step-1', '看看今天要完成什么', '今天我们要把小狐狸的第一次见面做成一个完整小故事。', ['when_start'], ['when_start']),
      step('step-2', '先让角色出场', '先接好“开始时”和“向右移动”，让小狐狸走上舞台。', ['when_start', 'move_right', 'say_line'], ['when_start', 'move_right']),
      step('step-3', '再让角色打招呼', '在移动后面接一句欢迎的话，让故事继续往前走。', ['when_start', 'move_right', 'say_line'], ['when_start', 'move_right', 'say_line']),
      step('step-4', '调整顺序让故事完整', '确认小狐狸是先出场，再说话，这样第一次见面会更自然。', ['when_start', 'move_right', 'say_line'], ['when_start', 'move_right', 'say_line']),
      step('step-5', '回看第一个完整小故事', '点一下运行，看看小狐狸是不是已经做出了第一个完整故事。', ['when_start', 'move_right', 'say_line'], ['when_start', 'move_right', 'say_line']),
    ],
    rewardCardId: 'growth-first-project',
    phase: 'trial',
    mode: 'guided',
    sortOrder: 3,
    hintLayers: buildHintLayers(
      '先让小狐狸出场，再让它开口打招呼。',
      '顺序要是“开始时 → 向右移动 → 说一句话”。',
      '先看一个顺序示意，再回来把故事接完整。',
    ),
    templateId: 'forest-meetup-stage',
    parentAdvice: '和孩子一起回看第一个作品，问问他先看到了什么、又听到了什么。',
  },
  {
    id: 'lesson-04-meadow-scene',
    title: '从森林走到草地',
    goal: '学会把故事从一个场景切换到另一个场景。',
    recommendedLevel: 'starter',
    steps: [
      step('step-1', '先看看两个画面', '先认识森林和草地两个画面，等会儿我们要让故事换一个地方。', ['when_start'], ['when_start']),
      step('step-2', '先把森林里的开场接好', '先接好“开始时”和“向右移动”，让小动物从森林里出发。', ['when_start', 'move_right'], ['when_start', 'move_right']),
      step('step-3', '认识切换场景积木', '这块“切换场景”积木可以让故事从森林走到草地。', ['when_start', 'move_right', 'switch_scene'], ['when_start', 'move_right']),
      step('step-4', '接上草地场景', '把“切换场景”接在后面，让故事真的来到草地。', ['when_start', 'move_right', 'switch_scene'], ['when_start', 'move_right', 'switch_scene']),
      step('step-5', '回看第一次转场', '点一下运行，看看故事是不是已经从森林走到草地了。', ['when_start', 'move_right', 'switch_scene'], ['when_start', 'move_right', 'switch_scene']),
    ],
    rewardCardId: 'theme-meadow-bird',
    phase: 'trial',
    mode: 'guided',
    sortOrder: 4,
    hintLayers: buildHintLayers(
      '先把森林里的开场接好，再把场景切到草地。',
      '顺序是“开始时 → 向右移动 → 切换场景”。',
      '先看一下故事怎么从森林走到草地，再回来试一次。',
    ),
    parentAdvice: '请孩子指给你看，故事是在第几步从森林走到了草地。',
  },
  {
    id: 'lesson-05-meadow-order',
    title: '旅行要按顺序发生',
    goal: '让故事按顺序先出发、再到达、最后说出旅行感受。',
    recommendedLevel: 'starter',
    steps: [
      step('step-1', '回顾上节的转场', '先看一眼故事怎么从森林走到草地，今天我们要让它更有先后顺序。', ['when_start'], ['when_start']),
      step('step-2', '先安排出发', '先让小动物从森林里出发，把第一段动作接好。', ['when_start', 'move_right', 'switch_scene', 'say_line'], ['when_start', 'move_right']),
      step('step-3', '再安排到达', '接上切换场景，让小动物来到草地。', ['when_start', 'move_right', 'switch_scene', 'say_line'], ['when_start', 'move_right', 'switch_scene']),
      step('step-4', '最后说出旅行感受', '在转场后面接一句旅行感受，让故事更像真的完成了一段旅程。', ['when_start', 'move_right', 'switch_scene', 'say_line'], ['when_start', 'move_right', 'switch_scene', 'say_line']),
      step('step-5', '顺序排完整', '再运行一次，看看是不是先出发、再到草地、最后才说出感受。', ['when_start', 'move_right', 'switch_scene', 'say_line'], ['when_start', 'move_right', 'switch_scene', 'say_line']),
    ],
    rewardCardId: 'growth-meadow-order',
    phase: 'trial',
    mode: 'guided',
    sortOrder: 5,
    hintLayers: buildHintLayers(
      '先安排出发，再安排到达，最后再说一句旅行感受。',
      '顺序要是“开始时 → 向右移动 → 切换场景 → 说一句话”。',
      '先看一个顺序示意，再回来把旅行接完整。',
    ),
    parentAdvice: '让孩子按顺序说一遍，先发生了什么，再发生了什么。',
  },
  {
    id: 'lesson-06-meadow-story',
    title: '小动物旅行记',
    goal: '把动作、转场和对白连起来，完成第二个完整小故事。',
    recommendedLevel: 'starter',
    steps: [
      step('step-1', '看看今天的旅行故事', '今天我们要把出发、转场和旅行感受接起来，做成第二个完整小故事。', ['when_start'], ['when_start']),
      step('step-2', '让小动物先出发', '先接好开始和移动，让小动物从森林里出发。', ['when_start', 'move_right', 'say_line', 'switch_scene'], ['when_start', 'move_right']),
      step('step-3', '让故事走到新场景', '把切换场景接上去，让故事来到草地。', ['when_start', 'move_right', 'say_line', 'switch_scene'], ['when_start', 'move_right', 'switch_scene']),
      step('step-4', '给旅行加一句收尾的话', '在转场后面接一句旅行感受，让故事像真的走完了一段旅程。', ['when_start', 'move_right', 'say_line', 'switch_scene'], ['when_start', 'move_right', 'switch_scene', 'say_line']),
      step('step-5', '回看我的旅行故事', '点一下运行，看看小动物是不是已经完成了一次小旅行。', ['when_start', 'move_right', 'say_line', 'switch_scene'], ['when_start', 'move_right', 'switch_scene', 'say_line']),
    ],
    rewardCardId: 'theme-meadow-story',
    phase: 'trial',
    mode: 'guided',
    sortOrder: 6,
    hintLayers: buildHintLayers(
      '先让小动物出发，再转到草地，最后给旅行收尾。',
      '把出发、转场和收尾的话都接好，旅行故事就完整了。',
      '先看一下完整旅行故事的顺序，再回来把自己的故事接完。',
    ),
    templateId: 'meadow-journey-stage',
    parentAdvice: '和孩子一起回看旅行故事，问问他小动物先在哪里、后来又到了哪里。',
  },
  {
    id: 'lesson-07-garden-click',
    title: '点一下，蝴蝶飞起来',
    goal: '学会让角色在被点击时做出反应。',
    recommendedLevel: 'foundation',
    steps: [
      step('step-1', '认识今天的新规则', '今天蝴蝶不会一开始就自己动，要等你点到它，它才会回应你。', ['when_clicked'], ['when_clicked']),
      step('step-2', '认识被点击时积木', '这块“被点击时”积木会告诉蝴蝶：只有被点到时才开始动作。', ['when_clicked'], ['when_clicked']),
      step('step-3', '先把点击开关放好', '先把“被点击时”放在最前面，让蝴蝶准备好回应点击。', ['when_clicked'], ['when_clicked']),
      step('step-4', '接上移动积木', '接上移动积木，让蝴蝶被点到后飞起来。', ['when_clicked', 'move_right'], ['when_clicked', 'move_right']),
      step('step-5', '试试点一下会发生什么', '点一下蝴蝶，看看它是不是已经会立刻飞起来了。', ['when_clicked', 'move_right'], ['when_clicked', 'move_right']),
    ],
    rewardCardId: 'theme-garden-butterfly',
    phase: 'trial',
    mode: 'guided',
    sortOrder: 7,
    hintLayers: buildHintLayers(
      '先放好“被点击时”，再让角色做动作。',
      '把“被点击时”放在最前面，再把动作积木接在后面。',
      '先看一下点到角色后才会开始动作的小示意。',
    ),
    parentAdvice: '请孩子演示一下点哪里会发生变化，再说说为什么会动起来。',
  },
  {
    id: 'lesson-08-garden-dialogue',
    title: '点一下，再说一句话',
    goal: '让角色在点击后先动起来，再说一句话回应你。',
    recommendedLevel: 'foundation',
    steps: [
      step('step-1', '回顾上节的互动动作', '先想一想：点一下蝴蝶后，它是不是先飞起来了？今天我们要让它再说一句话。', ['when_clicked'], ['when_clicked']),
      step('step-2', '先准备点击开关', '先把“被点击时”放在最前面，让蝴蝶准备好回应点击。', ['when_clicked'], ['when_clicked']),
      step('step-3', '点一下先动起来', '把移动积木接在后面，让角色先动起来。', ['when_clicked', 'move_right', 'say_line'], ['when_clicked', 'move_right']),
      step('step-4', '再接一句回应的话', '在动作后面接一句回应的话，让角色先动再说。', ['when_clicked', 'move_right', 'say_line'], ['when_clicked', 'move_right', 'say_line']),
      step('step-5', '回看完整互动', '点一下角色，看看它是不是已经会先动起来，再说一句话了。', ['when_clicked', 'move_right', 'say_line'], ['when_clicked', 'move_right', 'say_line']),
    ],
    rewardCardId: 'growth-garden-response',
    phase: 'trial',
    mode: 'guided',
    sortOrder: 8,
    hintLayers: buildHintLayers(
      '先让角色在点击后动起来，再接一句回应的话。',
      '顺序要是“被点击时 → 向右移动 → 说一句话”。',
      '先看一下“点一下，先动再说”的小示意。',
    ),
    parentAdvice: '和孩子一起试试不同的点法，看看角色会不会都做出相同反应。',
  },
  {
    id: 'lesson-09-garden-story',
    title: '花园里的互动表演',
    goal: '完成一个点一下就会有反应的互动故事。',
    recommendedLevel: 'foundation',
    steps: [
      step('step-1', '看看今天要完成什么', '今天我们要做一段完整的互动表演，让角色在花园里回应你的点击。', ['when_clicked'], ['when_clicked']),
      step('step-2', '先搭好互动开关', '先把“被点击时”放在最前面，告诉角色什么时候开始表演。', ['when_clicked'], ['when_clicked']),
      step('step-3', '点一下，角色先动起来', '接上动作积木，让角色在被点到后先动起来。', ['when_clicked', 'move_right', 'say_line'], ['when_clicked', 'move_right']),
      step('step-4', '再加上一句回应的话', '在动作后面接一句回应的话，让互动故事更完整。', ['when_clicked', 'move_right', 'say_line'], ['when_clicked', 'move_right', 'say_line']),
      step('step-5', '回看我的互动故事', '点一下角色，看看花园里的互动表演是不是已经会回应你了。', ['when_clicked', 'move_right', 'say_line'], ['when_clicked', 'move_right', 'say_line']),
    ],
    rewardCardId: 'theme-garden-story',
    phase: 'trial',
    mode: 'guided',
    sortOrder: 9,
    hintLayers: buildHintLayers(
      '先把点击开关放好，再接动作和回应的话。',
      '顺序要是“被点击时 → 向右移动 → 说一句话”。',
      '先看一下完整互动故事的顺序，再回来把自己的表演接完。',
    ),
    templateId: 'garden-interaction-stage',
    parentAdvice: '请孩子给你演示一遍互动故事，再告诉你点哪里才会触发变化。',
  },
  {
    id: 'lesson-10-second-friend',
    title: '第二位朋友上场',
    goal: '让第二位朋友也拥有自己的开始和动作顺序。',
    recommendedLevel: 'foundation',
    steps: [
      step('step-1', '看看今天的新朋友', '今天不是换掉原来的角色，而是让第二位动物朋友也来到舞台上。', ['when_start'], ['when_start']),
      step('step-2', '先让第一位朋友准备好', '先用熟悉的开始和动作，安排第一位朋友站上舞台。', ['when_start', 'move_right'], ['when_start', 'move_right']),
      step('step-3', '认识第二位朋友的开始', '第二位朋友也要有自己的开始积木，这样它才知道什么时候上场。', ['when_start', 'move_right', 'switch_character'], ['when_start', 'switch_character']),
      step('step-4', '接上第二位朋友的动作', '给第二位朋友接一个动作，让它也真正走上舞台。', ['when_start', 'move_right', 'switch_character'], ['when_start', 'move_right', 'switch_character']),
      step('step-5', '回看两个朋友都准备好了', '点一下运行，看看两位朋友是不是都已经站上了舞台。', ['when_start', 'move_right', 'switch_character'], ['when_start', 'move_right', 'switch_character']),
    ],
    rewardCardId: 'theme-duo-bear',
    phase: 'trial',
    mode: 'template',
    sortOrder: 10,
    hintLayers: buildHintLayers(
      '先安排第一位朋友，再让第二位朋友也准备好上场。',
      '第二位朋友也要有自己的开始积木和动作积木。',
      '先看一下两位朋友各自准备好的示意。',
    ),
    templateId: 'forest-graduation-show',
    parentAdvice: '请孩子告诉你哪一位朋友先准备好，第二位朋友又是怎么上场的。',
  },
  {
    id: 'lesson-11-duo-rehearsal',
    title: '两个朋友一起出发',
    goal: '让两个角色按顺序配合行动，像在一起完成一件小事。',
    recommendedLevel: 'foundation',
    steps: [
      step('step-1', '回顾两位朋友都在舞台上', '先看看两位朋友是不是都准备好了，再继续安排他们一起行动。', ['when_start', 'move_right', 'switch_character'], ['when_start', 'move_right', 'switch_character']),
      step('step-2', '先安排第一位朋友行动', '先让第一位朋友做出一个动作，带着故事往前走。', ['when_start', 'move_right', 'switch_character'], ['when_start', 'move_right']),
      step('step-3', '再安排第二位朋友跟上', '切换到第二位朋友，再让它接着行动，这样故事会更像合作。', ['when_start', 'move_right', 'switch_character'], ['when_start', 'move_right', 'switch_character']),
      step('step-4', '看看顺序是不是刚刚好', '确认是第一位朋友先动，第二位朋友再跟上，这样画面会更自然。', ['when_start', 'move_right', 'switch_character'], ['when_start', 'move_right', 'switch_character']),
      step('step-5', '回看两个朋友一起行动', '点一下运行，看看两位朋友是不是已经会按顺序一起行动了。', ['when_start', 'move_right', 'switch_character'], ['when_start', 'move_right', 'switch_character']),
    ],
    rewardCardId: 'growth-duo-teamwork',
    phase: 'trial',
    mode: 'template',
    sortOrder: 11,
    hintLayers: buildHintLayers(
      '先让第一位朋友行动，再让第二位朋友跟上。',
      '两位朋友不能共用一条开始线，每个人都要接好自己的动作。',
      '先看一下两位朋友按顺序合作的小示意。',
    ),
    templateId: 'forest-graduation-show',
    parentAdvice: '和孩子一起看看是谁先出发、谁后跟上，鼓励他调整顺序再试一次。',
  },
  {
    id: 'lesson-12-graduation-show',
    title: '一起找到小礼物',
    goal: '完成启蒙毕业作品，让两个角色先后出场，最后一起找到目标。',
    recommendedLevel: 'foundation',
    steps: [
      step('step-1', '看看今天的毕业故事', '今天我们要把两位朋友的动作接成一个完整故事，一起找到舞台上的小礼物。', ['when_start', 'move_right', 'switch_character'], ['when_start']),
      step('step-2', '让第一位朋友先出场', '先安排第一位朋友走上舞台，带着故事开始。', ['when_start', 'move_right', 'switch_character'], ['when_start', 'move_right']),
      step('step-3', '让第二位朋友跟着出场', '切换到第二位朋友，再让它也走上舞台，和第一位朋友汇合。', ['when_start', 'move_right', 'switch_character'], ['when_start', 'move_right', 'switch_character']),
      step('step-4', '让两个朋友一起找到目标', '把两位朋友的动作顺序接完整，让他们一起靠近小礼物。', ['when_start', 'move_right', 'say_line', 'switch_character'], ['when_start', 'move_right', 'switch_character']),
      step('step-5', '回看我的启蒙毕业作品', '点一下运行，看看两位朋友是不是已经一起找到了小礼物。', ['when_start', 'move_right', 'say_line', 'switch_character'], ['when_start', 'move_right', 'switch_character']),
    ],
    rewardCardId: 'commemorative-foundation-graduate',
    phase: 'trial',
    mode: 'template',
    sortOrder: 12,
    hintLayers: buildHintLayers(
      '先让第一位朋友出场，再让第二位朋友跟上。',
      '每个角色都要接好自己的开始和动作顺序。',
      '先看一下两位朋友一起找到目标的示意。',
    ),
    templateId: 'forest-graduation-show',
    parentAdvice: '和孩子一起回看毕业作品，问一问哪位朋友先出场，他们又是怎么一起找到小礼物的。',
  },
]

applyFoundationVoiceovers(launchLessons)
