import type {
  LaunchLessonDefinition,
  ProjectTemplateDefinition,
} from '@/features/domain/types'

const defaultHintLayers = [
  {
    id: 'repeat-goal',
    mode: 'repeat_goal' as const,
    copy: '再听一遍目标，先完成眼前这一步。',
  },
  {
    id: 'show-block',
    mode: 'show_block' as const,
    copy: '看一下高亮积木，把它放到正确位置。',
  },
  {
    id: 'offer-remedial',
    mode: 'offer_remedial' as const,
    copy: '先学一个小课，再回来继续。',
    remedialLessonId: 'remedial-click-trigger',
  },
]

export const launchTemplates: ProjectTemplateDefinition[] = [
  {
    id: 'forest-friendship',
    name: '森林友谊故事',
    starterScene: 'forest',
    starterCharacters: ['cat', 'bird'],
  },
  {
    id: 'space-rescue',
    name: '太空救援故事',
    starterScene: 'space',
    starterCharacters: ['robot', 'star'],
  },
]

export const launchLessons: LaunchLessonDefinition[] = [
  {
    id: 'trial-01-move-character',
    title: '让角色动起来',
    goal: '主角从左边走到右边',
    recommendedLevel: 'starter',
    steps: [
      {
        id: 'step-1',
        title: '放入开始积木',
        instruction: '先放一个“开始时”，告诉角色什么时候出发。',
        allowedBlocks: ['when_start', 'move_right'],
        requiredBlockTypes: ['when_start'],
      },
      {
        id: 'step-2',
        title: '让角色向右移动',
        instruction: '把“向右移动”接在后面，让角色走起来。',
        allowedBlocks: ['when_start', 'move_right'],
        requiredBlockTypes: ['when_start', 'move_right'],
      },
    ],
    rewardCardId: 'theme-scout-cat',
    phase: 'trial',
    mode: 'guided',
    sortOrder: 1,
    hintLayers: defaultHintLayers,
  },
  {
    id: 'trial-02-dialogue-action',
    title: '让角色说话和做动作',
    goal: '角色边走边说一句话',
    recommendedLevel: 'starter',
    steps: [
      {
        id: 'step-1',
        title: '先准备开始积木',
        instruction: '先放“开始时”。',
        allowedBlocks: ['when_start', 'say_line'],
        requiredBlockTypes: ['when_start'],
      },
      {
        id: 'step-2',
        title: '让角色说话',
        instruction: '把“说你好呀”接在后面。',
        allowedBlocks: ['when_start', 'say_line'],
        requiredBlockTypes: ['when_start', 'say_line'],
      },
    ],
    rewardCardId: 'theme-dialogue-bird',
    phase: 'trial',
    mode: 'guided',
    sortOrder: 2,
    hintLayers: defaultHintLayers,
  },
  {
    id: 'trial-03-scene-story',
    title: '做出第一个完整小故事',
    goal: '完成一个可回放的短故事',
    recommendedLevel: 'starter',
    steps: [
      {
        id: 'step-1',
        title: '开始讲故事',
        instruction: '先放“开始时”。',
        allowedBlocks: ['when_start', 'say_line', 'move_right'],
        requiredBlockTypes: ['when_start'],
      },
      {
        id: 'step-2',
        title: '让角色先说话',
        instruction: '接上“说你好呀”。',
        allowedBlocks: ['when_start', 'say_line', 'move_right'],
        requiredBlockTypes: ['when_start', 'say_line'],
      },
      {
        id: 'step-3',
        title: '让角色走起来',
        instruction: '最后接上“向右移动”，让故事动起来。',
        allowedBlocks: ['when_start', 'say_line', 'move_right'],
        requiredBlockTypes: ['when_start', 'say_line', 'move_right'],
      },
    ],
    rewardCardId: 'growth-first-project',
    phase: 'trial',
    mode: 'guided',
    sortOrder: 3,
    hintLayers: defaultHintLayers,
  },
  {
    id: 'course-04-two-characters',
    title: '让两个角色一起表演',
    goal: '安排两个角色先后出场',
    recommendedLevel: 'starter',
    steps: [
      {
        id: 'step-1',
        title: '继续安排表演',
        instruction: '先把“开始时”和一个动作排好。',
        allowedBlocks: ['when_start', 'move_right', 'say_line'],
        requiredBlockTypes: ['when_start', 'move_right'],
      },
    ],
    rewardCardId: 'theme-stage-duo',
    phase: 'course',
    mode: 'guided',
    sortOrder: 4,
    hintLayers: defaultHintLayers,
  },
  {
    id: 'course-05-scene-change',
    title: '让场景切换起来',
    goal: '在故事中切换两个场景',
    recommendedLevel: 'starter',
    steps: [
      {
        id: 'step-1',
        title: '切换新的场景动作',
        instruction: '先放开始，再让角色说一句话。',
        allowedBlocks: ['when_start', 'say_line'],
        requiredBlockTypes: ['when_start', 'say_line'],
      },
    ],
    rewardCardId: 'theme-scene-switch',
    phase: 'course',
    mode: 'guided',
    sortOrder: 5,
    hintLayers: defaultHintLayers,
  },
  {
    id: 'course-06-repeat-motion',
    title: '让动作重复出现',
    goal: '让角色重复做动作',
    recommendedLevel: 'starter',
    steps: [
      {
        id: 'step-1',
        title: '重复一个动作',
        instruction: '先用开始和移动，做出重复前的动作。',
        allowedBlocks: ['when_start', 'move_right'],
        requiredBlockTypes: ['when_start', 'move_right'],
      },
    ],
    rewardCardId: 'growth-repeat-master',
    phase: 'course',
    mode: 'guided',
    sortOrder: 6,
    hintLayers: defaultHintLayers,
  },
  {
    id: 'course-07-click-trigger',
    title: '点一下就发生事情',
    goal: '让点击触发角色动作',
    recommendedLevel: 'foundation',
    steps: [
      {
        id: 'step-1',
        title: '点击前先准备',
        instruction: '先排好开始和说话积木。',
        allowedBlocks: ['when_start', 'say_line'],
        requiredBlockTypes: ['when_start', 'say_line'],
      },
    ],
    rewardCardId: 'growth-click-trigger',
    phase: 'course',
    mode: 'guided',
    sortOrder: 7,
    hintLayers: defaultHintLayers,
  },
  {
    id: 'course-08-order-events',
    title: '排好故事顺序',
    goal: '让多个事件按顺序发生',
    recommendedLevel: 'foundation',
    steps: [
      {
        id: 'step-1',
        title: '把顺序排好',
        instruction: '先从开始、说话、移动三个积木开始。',
        allowedBlocks: ['when_start', 'say_line', 'move_right'],
        requiredBlockTypes: ['when_start', 'say_line', 'move_right'],
      },
    ],
    rewardCardId: 'theme-story-order',
    phase: 'course',
    mode: 'guided',
    sortOrder: 8,
    hintLayers: defaultHintLayers,
  },
  {
    id: 'course-09-character-teamwork',
    title: '让角色配合起来',
    goal: '完成双角色互动',
    recommendedLevel: 'foundation',
    steps: [
      {
        id: 'step-1',
        title: '安排角色配合',
        instruction: '用开始和说话先安排第一位角色。',
        allowedBlocks: ['when_start', 'say_line'],
        requiredBlockTypes: ['when_start', 'say_line'],
      },
    ],
    rewardCardId: 'theme-teamwork',
    phase: 'course',
    mode: 'guided',
    sortOrder: 9,
    hintLayers: defaultHintLayers,
  },
  {
    id: 'course-10-simple-choice',
    title: '故事里出现选择',
    goal: '做出一个简单分支',
    recommendedLevel: 'foundation',
    steps: [
      {
        id: 'step-1',
        title: '做出一个选择',
        instruction: '先把开始和移动准备好。',
        allowedBlocks: ['when_start', 'move_right'],
        requiredBlockTypes: ['when_start', 'move_right'],
      },
    ],
    rewardCardId: 'growth-choice-maker',
    phase: 'course',
    mode: 'guided',
    sortOrder: 10,
    hintLayers: defaultHintLayers,
  },
  {
    id: 'course-11-rhythm-control',
    title: '控制故事节奏',
    goal: '让动作和对白更有节奏',
    recommendedLevel: 'foundation',
    steps: [
      {
        id: 'step-1',
        title: '调整故事节奏',
        instruction: '先用开始、说话、移动排出节奏。',
        allowedBlocks: ['when_start', 'say_line', 'move_right'],
        requiredBlockTypes: ['when_start', 'say_line', 'move_right'],
      },
    ],
    rewardCardId: 'theme-rhythm-star',
    phase: 'course',
    mode: 'guided',
    sortOrder: 11,
    hintLayers: defaultHintLayers,
  },
  {
    id: 'course-12-story-polish',
    title: '把故事打磨完整',
    goal: '补齐开头和结尾',
    recommendedLevel: 'foundation',
    steps: [
      {
        id: 'step-1',
        title: '补齐故事结尾',
        instruction: '用开始和说话补上结尾。',
        allowedBlocks: ['when_start', 'say_line'],
        requiredBlockTypes: ['when_start', 'say_line'],
      },
    ],
    rewardCardId: 'growth-story-polish',
    phase: 'course',
    mode: 'guided',
    sortOrder: 12,
    hintLayers: defaultHintLayers,
  },
  {
    id: 'course-13-template-story-start',
    title: '按模板做自己的故事',
    goal: '在模板里替换角色和场景',
    recommendedLevel: 'foundation',
    steps: [
      {
        id: 'step-1',
        title: '先套用故事模板',
        instruction: '先用开始和说话启动模板。',
        allowedBlocks: ['when_start', 'say_line'],
        requiredBlockTypes: ['when_start', 'say_line'],
      },
    ],
    rewardCardId: 'theme-template-explorer',
    phase: 'course',
    mode: 'template',
    sortOrder: 13,
    hintLayers: defaultHintLayers,
    templateId: 'forest-friendship',
  },
  {
    id: 'course-14-template-story-edit',
    title: '给故事加对白和动作',
    goal: '丰富模板故事内容',
    recommendedLevel: 'foundation',
    steps: [
      {
        id: 'step-1',
        title: '给模板加动作',
        instruction: '在模板里再加一个移动动作。',
        allowedBlocks: ['when_start', 'say_line', 'move_right'],
        requiredBlockTypes: ['when_start', 'say_line', 'move_right'],
      },
    ],
    rewardCardId: 'growth-story-editor',
    phase: 'course',
    mode: 'template',
    sortOrder: 14,
    hintLayers: defaultHintLayers,
    templateId: 'space-rescue',
  },
  {
    id: 'course-15-finish-story',
    title: '完成我的独立小故事',
    goal: '独立完成一个可回放小故事',
    recommendedLevel: 'foundation',
    steps: [
      {
        id: 'step-1',
        title: '完成独立小故事',
        instruction: '把开始、说话和动作排成你的完整故事。',
        allowedBlocks: ['when_start', 'say_line', 'move_right'],
        requiredBlockTypes: ['when_start', 'say_line', 'move_right'],
      },
    ],
    rewardCardId: 'commemorative-story-graduate',
    phase: 'course',
    mode: 'template',
    sortOrder: 15,
    hintLayers: defaultHintLayers,
  },
]
