import type { CardDefinition } from '@/features/domain/types'

export const cardDefinitions: CardDefinition[] = [
  {
    id: 'theme-scout-cat',
    name: '探险小猫',
    category: 'theme',
    rarity: 'common',
    series: '森林启程',
    rewardTags: ['lesson_1', 'starter'],
  },
  {
    id: 'growth-first-project',
    name: '我的第一部动画',
    category: 'growth',
    rarity: 'fine',
    series: '成长时刻',
    rewardTags: ['first_project'],
  },
  {
    id: 'growth-three-day-streak',
    name: '三天坚持之星',
    category: 'growth',
    rarity: 'rare',
    series: '成长时刻',
    rewardTags: ['streak_3'],
  },
  {
    id: 'theme-dialogue-bird',
    name: '对白小鸟',
    category: 'theme',
    rarity: 'common',
    series: '森林启程',
    rewardTags: ['trial_2'],
  },
  {
    id: 'theme-stage-duo',
    name: '双角色舞台卡',
    category: 'theme',
    rarity: 'common',
    series: '舞台故事',
    rewardTags: ['course_4'],
  },
  {
    id: 'theme-scene-switch',
    name: '场景切换卡',
    category: 'theme',
    rarity: 'common',
    series: '舞台故事',
    rewardTags: ['course_5'],
  },
  {
    id: 'growth-repeat-master',
    name: '重复动作小达人',
    category: 'growth',
    rarity: 'fine',
    series: '成长时刻',
    rewardTags: ['course_6'],
  },
  {
    id: 'growth-click-trigger',
    name: '点击触发小高手',
    category: 'growth',
    rarity: 'fine',
    series: '成长时刻',
    rewardTags: ['course_7'],
  },
  {
    id: 'theme-story-order',
    name: '故事顺序卡',
    category: 'theme',
    rarity: 'fine',
    series: '舞台故事',
    rewardTags: ['course_8'],
  },
  {
    id: 'theme-teamwork',
    name: '角色配合卡',
    category: 'theme',
    rarity: 'fine',
    series: '舞台故事',
    rewardTags: ['course_9'],
  },
  {
    id: 'growth-choice-maker',
    name: '分支选择小达人',
    category: 'growth',
    rarity: 'rare',
    series: '成长时刻',
    rewardTags: ['course_10'],
  },
  {
    id: 'theme-rhythm-star',
    name: '节奏控制之星',
    category: 'theme',
    rarity: 'rare',
    series: '舞台故事',
    rewardTags: ['course_11'],
  },
  {
    id: 'growth-story-polish',
    name: '故事打磨小高手',
    category: 'growth',
    rarity: 'rare',
    series: '成长时刻',
    rewardTags: ['course_12'],
  },
  {
    id: 'theme-template-explorer',
    name: '模板探险家',
    category: 'theme',
    rarity: 'fine',
    series: '创作工坊',
    rewardTags: ['course_13'],
  },
  {
    id: 'growth-story-editor',
    name: '故事编辑小达人',
    category: 'growth',
    rarity: 'rare',
    series: '创作工坊',
    rewardTags: ['course_14'],
  },
  {
    id: 'commemorative-story-graduate',
    name: '故事创作者纪念卡',
    category: 'commemorative',
    rarity: 'limited',
    series: '第一季纪念',
    rewardTags: ['story_path_complete'],
  },
]
