import type { CardDefinition } from '@/features/domain/types'

export const cardDefinitions: CardDefinition[] = [
  {
    id: 'theme-forest-fox',
    name: '森林小狐狸',
    category: 'theme',
    rarity: 'common',
    series: '森林见面会',
    rewardTags: ['lesson_01', 'unit_1'],
  },
  {
    id: 'theme-forest-rabbit',
    name: '问候小兔子',
    category: 'theme',
    rarity: 'common',
    series: '森林见面会',
    rewardTags: ['lesson_02', 'unit_1'],
  },
  {
    id: 'growth-first-project',
    name: '我的第一部动画',
    category: 'growth',
    rarity: 'fine',
    series: '成长时刻',
    rewardTags: ['lesson_03', 'first_project'],
  },
  {
    id: 'theme-meadow-bird',
    name: '草地小鸟',
    category: 'theme',
    rarity: 'common',
    series: '小动物去旅行',
    rewardTags: ['lesson_04', 'unit_2'],
  },
  {
    id: 'growth-meadow-order',
    name: '旅行顺序小达人',
    category: 'growth',
    rarity: 'fine',
    series: '成长时刻',
    rewardTags: ['lesson_05', 'unit_2'],
  },
  {
    id: 'theme-meadow-story',
    name: '草地旅行纪念卡',
    category: 'theme',
    rarity: 'fine',
    series: '小动物去旅行',
    rewardTags: ['lesson_06', 'unit_2_story'],
  },
  {
    id: 'theme-garden-butterfly',
    name: '花园小蝴蝶',
    category: 'theme',
    rarity: 'common',
    series: '花园互动秀',
    rewardTags: ['lesson_07', 'unit_3'],
  },
  {
    id: 'growth-garden-response',
    name: '互动回应小高手',
    category: 'growth',
    rarity: 'fine',
    series: '成长时刻',
    rewardTags: ['lesson_08', 'unit_3'],
  },
  {
    id: 'theme-garden-story',
    name: '花园互动演出卡',
    category: 'theme',
    rarity: 'fine',
    series: '花园互动秀',
    rewardTags: ['lesson_09', 'unit_3_story'],
  },
  {
    id: 'theme-duo-bear',
    name: '第二位朋友小熊',
    category: 'theme',
    rarity: 'fine',
    series: '动物朋友合作演出',
    rewardTags: ['lesson_10', 'unit_4'],
  },
  {
    id: 'growth-duo-teamwork',
    name: '双角色配合小达人',
    category: 'growth',
    rarity: 'rare',
    series: '成长时刻',
    rewardTags: ['lesson_11', 'unit_4'],
  },
  {
    id: 'commemorative-foundation-graduate',
    name: '启蒙毕业纪念卡',
    category: 'commemorative',
    rarity: 'limited',
    series: '启蒙毕业季',
    rewardTags: ['lesson_12', 'foundation_graduate'],
  },
  {
    id: 'growth-three-day-streak',
    name: '三天坚持之星',
    category: 'growth',
    rarity: 'rare',
    series: '成长时刻',
    rewardTags: ['streak_3'],
  },
]
