import type { CardDefinition } from '@/features/domain/types'

export const cardDefinitions: CardDefinition[] = [
  {
    id: 'theme-forest-fox',
    name: '森林小狐狸',
    category: 'theme',
    rarity: 'common',
    series: '森林见面会',
    rewardTags: ['lesson-01-forest-hello'],
  },
  {
    id: 'theme-forest-rabbit',
    name: '问候小兔子',
    category: 'theme',
    rarity: 'common',
    series: '森林见面会',
    rewardTags: ['lesson-02-forest-greeting'],
  },
  {
    id: 'growth-first-project',
    name: '我的第一部动画',
    category: 'growth',
    rarity: 'fine',
    series: '成长时刻',
    rewardTags: ['lesson-03-forest-story'],
  },
  {
    id: 'theme-meadow-bird',
    name: '草地小鸟',
    category: 'theme',
    rarity: 'common',
    series: '小动物去旅行',
    rewardTags: ['lesson-04-meadow-scene'],
  },
  {
    id: 'growth-meadow-order',
    name: '旅行顺序小达人',
    category: 'growth',
    rarity: 'fine',
    series: '小动物去旅行',
    rewardTags: ['lesson-05-meadow-order'],
  },
  {
    id: 'theme-meadow-story',
    name: '草地旅行纪念卡',
    category: 'theme',
    rarity: 'rare',
    series: '小动物去旅行',
    rewardTags: ['lesson-06-meadow-story'],
  },
  {
    id: 'theme-garden-butterfly',
    name: '花园小蝴蝶',
    category: 'theme',
    rarity: 'common',
    series: '花园互动秀',
    rewardTags: ['lesson-07-garden-click'],
  },
  {
    id: 'growth-garden-response',
    name: '互动回应小高手',
    category: 'growth',
    rarity: 'fine',
    series: '花园互动秀',
    rewardTags: ['lesson-08-garden-dialogue'],
  },
  {
    id: 'theme-garden-story',
    name: '花园互动演出卡',
    category: 'theme',
    rarity: 'rare',
    series: '花园互动秀',
    rewardTags: ['lesson-09-garden-story'],
  },
  {
    id: 'theme-duo-bear',
    name: '第二位朋友小熊',
    category: 'theme',
    rarity: 'common',
    series: '动物朋友合作演出',
    rewardTags: ['lesson-10-second-friend'],
  },
  {
    id: 'growth-duo-teamwork',
    name: '双角色配合小达人',
    category: 'growth',
    rarity: 'fine',
    series: '动物朋友合作演出',
    rewardTags: ['lesson-11-duo-rehearsal'],
  },
  {
    id: 'commemorative-foundation-graduate',
    name: '启蒙毕业纪念卡',
    category: 'commemorative',
    rarity: 'limited',
    series: '启蒙毕业季',
    rewardTags: ['lesson-12-graduation-show'],
  },
  {
    id: 'growth-three-day-streak',
    name: '三天坚持之星',
    category: 'growth',
    rarity: 'rare',
    series: '成长时刻',
    rewardTags: ['streak-3'],
  },
]
